name: CI

on:
  push:
    branches: [development]

jobs:
  test:
    name: Package Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: |

          npm install
          npm run build
          npm run test
        env:
          XSERVER_TOKEN: ${{ secrets.XSERVER_TOKEN }}
          PRODUCT_ID: ${{ secrets.PRODUCT_ID }}
